#!/bin/sh

# Copyright (C) 2017, 2020 Marius Bakke
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

case "${OSP_COMMIT}" in
    "")
	;;
    *[\\\;\(\)$\&]*)
	echo "Nice try."
	exit 1
	;;
    *[!a-f0-9]*)
	echo "Commit must be a hexadecimal string."
	exit 1
	;;
    *)
	;;
esac

case "${OSP_BRANCH}" in
    "")
	;;
    *[\\\;\(\)$\&]*)
	echo "Not funny."
	exit 1
	;;
    *[!a-z0-9-]*)
	echo "Branch can only contain alphanumeric characters and '-'."
	exit 1
	;;
    *)
	;;
esac

case "${OSP_REPO_URI}" in
    "")
	;;
    *[\\\;\(\)$\&]*)
	echo "Pls stahp."
	exit 1
	;;
    *[!a-z0-9-_.:/]*)
	echo "Not a valid URL."
	exit 1
	;;
    *)
	;;
esac

case "${OSP_FILESYSTEM}" in
  ""|xfs|ext2|ext3|ext4|btrfs)
      ;;
  *)
    echo "Invalid value '$OSP_FILESYSTEM' for the filesystem parameter" 1>&2
    exit 1;
    ;;
esac

case "${OSP_LAYOUT}" in
  ""|basic|standard)
      ;;
  *)
    echo "Invalid value '$OSP_LAYOUT' for the layout parameter" 1>&2
    exit 1;
    ;;
esac

exit 0

